In [2]:
import numpy as np
import matplotlib.pyplot as plt
path = "../../inputs/"

a_min(Pantheon) = 0.306626 

a_min(BAO)      = 0.294118 

a_min(CMB)      = 0.00091659

a_min(QSO)      = 0.117078

In [1]:
a_min_sn = 0.306626 
a_min_bao = 0.294118 
a_min_cmb = 0.00091659
a_min_qso = 0.11708

z_max_sn = 1/a_min_sn - 1
z_max_bao = 1/a_min_bao - 1
z_max_qso = 1/a_min_qso - 1
z_max_cmb = 1/a_min_cmb - 1

print(f"z_max SN  : {z_max_sn}")
print(f"z_max BAO  : {z_max_bao}")
print(f"z_max QSO  : {z_max_qso}")
print(f"z_max CMB  : {z_max_cmb}")

z_max SN  : 2.2613020422273387
z_max BAO  : 2.399995920004896
z_max QSO  : 7.541168431841475
z_max CMB  : 1090.000338210105


z_max SN : 2.2613

z_max BAO : 2.40

z_max QSO : 7.5412

In [6]:
c_sn = np.array([1.34,-0.314,0.033])
c_sn_bao = np.array([1.307,-0.282,0.021])
c_sn_bao_qso = np.array([1.059,-0.2264])
c_sn_bao_cmb = np.array([0.1110,-0.02638])
c_all = np.array([0.1102, -0.0256])
cov_sn = np.loadtxt(path+"inv_fisher_matrix_sn")
cov_sn_bao = np.loadtxt(path+"inv_fisher_matrix_sn_bao")
cov_sn_bao_qso = np.loadtxt(path+"inv_fisher_matrix_sn_bao_qso.txt")
cov_sn_bao_cmb = np.loadtxt(path+"inv_fisher_matrix_sn_bao_cmb")
cov_all = np.loadtxt(path+"inv_fisher_matrix_all.txt")

L_sn = np.linalg.cholesky(cov_sn)
L_sn_bao = np.linalg.cholesky(cov_sn_bao)
L_sn_bao_qso = np.linalg.cholesky(cov_sn_bao_qso)
L_sn_bao_cmb = np.linalg.cholesky(cov_sn_bao_cmb)
L_all = np.linalg.cholesky(cov_all)

c_sn = np.linalg.inv(L_sn) @ c_sn
c_sn_bao = np.linalg.inv(L_sn_bao) @ c_sn_bao
c_sn_bao_qso = np.linalg.inv(L_sn_bao_qso) @ c_sn_bao_qso
c_sn_bao_cmb = np.linalg.inv(L_sn_bao_cmb) @ c_sn_bao_cmb
c_all = np.linalg.inv(L_all) @ c_all

print(f"SN                   : {c_sn}")
print(f"SN + BAO             : {c_sn_bao}")
print(f"SN + BAO + QSO       : {c_sn_bao_qso}")
print(f"SN + BAO + CMB       : {c_sn_bao_cmb}")
print(f"SN + BA0 + CMB + QSO : {c_all}")

SN                   : [ 24.49625109 248.81930777 229.88541429]
SN + BAO             : [ 52.77217502 333.26212524 178.70766496]
SN + BAO + QSO       : [ 94.82648446 370.23868677]
SN + BAO + CMB       : [ 91.94624081 371.64984302]
SN + BA0 + CMB + QSO : [ 91.94642035 372.09386794]


In [21]:
c_sn = L_sn @ c_sn
c_sn_bao = L_sn_bao @ c_sn_bao
c_sn_bao_cmb = L_sn_bao_cmb @ c_sn_bao_cmb
c_all = L_all @ c_all

print(f"SN                   : {c_sn}")
print(f"SN + BAO             : {c_sn_bao}")
print(f"SN + BAO + CMB       : {c_sn_bao_cmb}")
print(f"SN + BAO + CMB + QSO : {c_all}")

SN                   : [ 0.07330101 -0.08044883  0.03170315]
SN + BAO             : [ 0.03237026 -0.03653487  0.01565139]
SN + BAO + CMB       : [ 0.000134   -0.00011773]
SN + BAO + CMB + QSO : [ 0.1102 -0.0256]


In [ ]:
import numpy as np

# Load Fisher matrix
F = np.loadtxt("fisher_matrix.txt")

# Eigen decomposition
eigvals, eigvecs = np.linalg.eig(F)

# Inverse sqrt of eigenvalues
s = 1 / np.sqrt(eigvals)
print(f"correlated errors : {s}")

# Rotate back to parameter basis
dp = np.abs(eigvecs @ s)

print(f"uncorrelated errors : {dp}")  # Matches dp in C++


In [ ]:
invF = np.loadtxt("inv_fisher_matrix_qso.txt")

# Eigen decomposition
eigvals, eigvecs = np.linalg.eig(invF)
s = np.sqrt(eigvals)
print(f"correlated errors : {s}")

# Rotate back to parameter basis
dp = np.abs(eigvecs @ s)

print(f"uncorrelated errors : {dp}")  # Matches dp in C++


In [20]:
fisher = np.loadtxt("fisher_matrix.txt")
inv_fisher = np.linalg.inv(fisher)
print(inv_fisher)
eigvals, eigvecs = np.linalg.eigh(inv_fisher)
s = np.sqrt(eigvals)
err = np.abs(eigvecs.T @ s)
print("uncorr err",err)

# np.savetxt("inv_fisher_matrix_sn",inv_fisher)

[[ 0.00299234 -0.00322588  0.00121415]
 [-0.00322588  0.00349831 -0.00133534]
 [ 0.00121415 -0.00133534  0.00054309]]
uncorr err [0.03722289 0.07269758 0.01905912]


In [63]:
fisher = np.loadtxt("fisher_matrix_sn.txt")
inv_fisher = np.linalg.inv(fisher)
eigvals, eigvecs = np.linalg.eigh(fisher)
print(f"eigvals: {eigvals}")
print(f"eigvecs: \n {eigvecs}")
eigvecs[:,0]*=-1
# eigvecs[:,1]*=-1
s = np.sqrt(1/eigvals)
err = (eigvecs @ s)
print("uncorr err : ",err)

eigvals: [1.43131271e+02 2.28388527e+04 2.98201816e+05]
eigvecs: 
 [[-0.65331476 -0.45566333 -0.60460793]
 [ 0.70741617 -0.08291373 -0.70191715]
 [-0.26970761  0.88628226 -0.37651237]]
uncorr err :  [ 0.05048555 -0.060964    0.02771881]


In [9]:
# fisher = np.loadtxt(path+"inv_fisher_matrix_sn_bao_qso.txt")
# fisher = np.loadtxt(path+"inv_fisher_matrix_sn")
# fisher = np.loadtxt(path+"inv_fisher_matrix_sn_bao")
cov_sn_bao_qso = np.loadtxt(path+"inv_fisher_matrix_sn_bao_qso.txt")
# fisher = np.loadtxt(path+"inv_fisher_matrix_sn_bao_cmb")
# fisher = np.loadtxt(path+"inv_fisher_matrix_all.txt")
# fisher = inv_fisher
eigvals, eigvecs = np.linalg.eig(cov_sn_bao_qso)
print(1/eigvals)
print(f"eigvals: {eigvals}")
print(f"eigvecs: \n {eigvecs}")
# dum = eigvecs[:,1]
# eigvecs[:,1] = eigvecs[:,2]
# eigvecs[:,2] = dum
# eigvecs[:,0]*=-1
# eigvecs[:,2]*=-1
s = np.sqrt(eigvals)
err = (eigvecs @ s)
print("uncorr err : ",err)

[  4569.66658587 510659.05592584]
eigvals: [2.18834346e-04 1.95825373e-06]
eigvecs: 
 [[ 0.75235692  0.65875569]
 [-0.65875569  0.75235692]]
uncorr err :  [ 0.0120515  -0.00869218]


In [18]:
print(cov_sn)
print(cov_sn_bao)

[[ 0.00299234 -0.00322588  0.00121415]
 [-0.00322588  0.00349831 -0.00133534]
 [ 0.00121415 -0.00133534  0.00054309]]
[[ 0.0006134  -0.00067381  0.00027488]
 [-0.00067381  0.00075217 -0.00031502]
 [ 0.00027488 -0.00031502  0.00015243]]


In [58]:
inv_fisher == cov_sn

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
uncorr_c = np.array([1.3119953478217734, -0.07018497660756118,-0.04286029905080796, 0.1341693364083768])
uncorr_err = np.array([2.533042788505554, 0.6682854617169596,0.5209843092636741, 0.5968765213682778])
# fisher = np.loadtxt(path+"inv_fisher_matrix_sn_bao_qso.txt")
# fisher = np.loadtxt(path+"inv_fisher_matrix_sn")
# fisher = np.loadtxt(path+"inv_fisher_matrix_sn_bao")
# fisher = np.loadtxt(path+"inv_fisher_matrix_sn_bao_qso.txt")
# fisher = np.loadtxt(path+"inv_fisher_matrix_sn_bao_cmb")
# fisher = np.loadtxt(path+"inv_fisher_matrix_all.txt")

L = np.linalg.cholesky(fisher)
corr_c = L@uncorr_c
corr_err = L@uncorr_err
print(f"correlated coeffs : {corr_c}")
print(f"correlated error  : {corr_err}")

NameError: name 'fisher' is not defined

In [10]:
err = np.array([1.74, 1.83])
np.linalg.inv(eigvecs) @ err

array([0.10357812, 2.52304807])